# Generated by Django 4.1.7 on 2023-03-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex_one_movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='Movies',
        ),
    ]
