# Generated by Django 4.1.7 on 2023-03-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex_one_movies_app', '0004_director_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_in_min',
            field=models.IntegerField(blank=True, db_column='duration', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ex_one_movies_app.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(db_column='year'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_column='rating', db_index=True)),
                ('review_date', models.DateField(db_column='review_date')),
                ('review_text', models.CharField(blank=True, db_column='review_text', db_index=True, max_length=256, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ex_one_movies_app.movie')),
            ],
        ),
    ]
