# Generated by Django 4.1.7 on 2023-03-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex_one_movies_app', '0005_movie_duration_in_min_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ex_one_movies_app.director'),
        ),
    ]
