# Generated by Django 4.1.7 on 2023-03-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex_one_movies_app', '0006_alter_movie_director'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
