# Generated by Django 4.1.7 on 2023-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_one_movies_app', '0008_remove_review_review_date_review_review_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(db_column='rating', db_index=True),
        ),
        migrations.AlterModelTable(
            name='review',
            table='Reviews',
        ),
    ]
