# Generated by Django 4.1.7 on 2023-03-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_and_companies_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
