# Generated by Django 4.1.7 on 2023-03-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees_and_companies_app', '0003_alter_person_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_column='job title', db_index=True, max_length=128)),
                ('is_current_job', models.BooleanField(db_column='is current job', db_index=True)),
                ('company_email', models.CharField(db_column='company email', max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employees_and_companies_app.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employees_and_companies_app.person')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
    ]
